name: Build LaTeX document
on:
  push:
    branches-ignore:
      - 'orphan/lualatex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: GitHub Action for Lua LaTeX
        uses: xu-cheng/latex-action@3.1.0
        with:
          root_file: |
            gavinsdavies.tex
          latexmk_use_lualatex: true
      - name: Orphan branch commit
        run: |
          git checkout --orphan orphan/lualatex
          git rm -rf .
          git add gavinsdavies.pdf
          git -c user.name='GitHub Action' -c user.email='action@github.com' commit -m "Compiled and built pdf version of cv."
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: orphan/lualatex
          force: true